// Sample music library with free preview URLs
// In production, integrate with Spotify, Deezer, or your own audio CDN

const musicLibrary = [
  {
    id: '1',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    album: 'Divide',
    year: 2017,
    genre: ['Pop'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  {
    id: '2',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    year: 2020,
    genre: ['Pop', 'Synthwave'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  },
  {
    id: '3',
    title: 'Dance Monkey',
    artist: 'Tones and I',
    album: 'The Kids Are Coming',
    year: 2019,
    genre: ['Pop', 'Electropop'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: '4',
    title: 'Someone Like You',
    artist: 'Adele',
    album: '21',
    year: 2011,
    genre: ['Pop', 'Soul'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
  {
    id: '5',
    title: 'Uptown Funk',
    artist: 'Bruno Mars',
    album: 'Uptown Special',
    year: 2014,
    genre: ['Funk', 'Pop'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  },
  {
    id: '6',
    title: 'Hello',
    artist: 'Adele',
    album: '25',
    year: 2015,
    genre: ['Pop', 'Soul'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  },
  {
    id: '7',
    title: 'Thinking Out Loud',
    artist: 'Ed Sheeran',
    album: 'X',
    year: 2014,
    genre: ['Pop', 'Soul'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
  },
  {
    id: '8',
    title: 'Havana',
    artist: 'Camila Cabello',
    album: 'Camila',
    year: 2018,
    genre: ['Pop', 'Latin'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
  },
  {
    id: '9',
    title: 'Despacito',
    artist: 'Luis Fonsi',
    album: 'Vida',
    year: 2017,
    genre: ['Latin', 'Reggaeton'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
  },
  {
    id: '10',
    title: 'Old Town Road',
    artist: 'Lil Nas X',
    album: '7',
    year: 2019,
    genre: ['Country', 'Hip-Hop'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
  },
  {
    id: '11',
    title: 'Bad Guy',
    artist: 'Billie Eilish',
    album: 'When We All Fall Asleep, Where Do We Go?',
    year: 2019,
    genre: ['Pop', 'Electropop'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
  },
  {
    id: '12',
    title: 'Shallow',
    artist: 'Lady Gaga',
    album: 'A Star Is Born',
    year: 2018,
    genre: ['Pop', 'Rock'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
  },
  {
    id: '13',
    title: 'Rockstar',
    artist: 'Post Malone',
    album: 'Beerbongs & Bentleys',
    year: 2017,
    genre: ['Hip-Hop', 'Rap'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
  },
  {
    id: '14',
    title: 'Sunflower',
    artist: 'Post Malone',
    album: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    genre: ['Pop', 'Hip-Hop'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
  },
  {
    id: '15',
    title: 'God\'s Plan',
    artist: 'Drake',
    album: 'Scorpion',
    year: 2018,
    genre: ['Hip-Hop', 'Rap'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
  },
  {
    id: '16',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    album: 'Divide',
    year: 2017,
    genre: ['Pop', 'Ballad'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3',
  },
  {
    id: '17',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    year: 1975,
    genre: ['Rock', 'Classic Rock'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  {
    id: '18',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    year: 1982,
    genre: ['Pop', 'R&B'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  },
  {
    id: '19',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
    genre: ['Rock', 'Grunge'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: '20',
    title: 'Sweet Child O\' Mine',
    artist: 'Guns N\' Roses',
    album: 'Appetite for Destruction',
    year: 1987,
    genre: ['Rock', 'Hard Rock'],
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
];

module.exports = { musicLibrary };
